export enum DBSCANAlgorithmActionTypes {
    SET_MIN_POINTS = 'SET_MIN_POINTS',
    SET_EPSILON = 'SET_EPSILON',
    ADD_TO_RENDER = 'ADD_TO_RENDER',
    POP_RENDER = 'POP_RENDER',
    SET_RENDER = 'SET_RENDER',
    SET_SHOW_GUIDE_CIRCLE = 'SET_SHOW_GUIDE_CIRCLE',
    APPEND_TO_RENDER='APPEND_TO_RENDER'
}

export default DBSCANAlgorithmActionTypes;
