export enum GlobalActionTypes {
    SET_COORDINATES_OF_NODES = 'SET_COORDINATES_OF_NODES',
    SET_ALGORITHM = 'SET_ALGORITHM',
    RESET = 'RESET',
    START_VISUALIZATION = 'START_VISUALIZATION',
    END_VISUALIZATION = 'END_VISUALIZATION',
    SET_SPEED = 'SET_SPEED',
    UPDATE_COORDINATES = 'UPDATE_COORDINATES',
    SET_OPEN_FAB = 'SET_OPEN_FAB',
    ADD_LOG='ADD_LOG',
    CLEAR_LOGS='CLEAR_LOGS',
    SET_LOGS='SET_LOGS'
}

export default GlobalActionTypes;
