export enum GlobalActionTypes {
    SET_COORDINATES_OF_NODES = 'SET_COORDINATES_OF_NODES',
    SET_ALGORITHM = 'SET_ALGORITHM',
    RESET = 'RESET',
    START_VISUALIZATION = 'START_VISUALIZATION',
    END_VISUALIZATION = 'END_VISUALIZATION',
    SET_SPEED = 'SET_SPEED',
    UPDATE_COORDINATES = 'UPDATE_COORDINATES',
    SET_REF_TO_BOARD = 'SET_REF_TO_BOARD',
}

export default GlobalActionTypes;
