export enum AlgorithmNames {
    KMEANS = 'KMEANS',
    DBSCAN = 'DBSCAN',
    MEAN_SHIFT = 'MEAN SHIFT',
    HIERARCHICAL_CLUSTERING_AGGLOMERATIVE='AGGLOMERATIVE HIERARCHICAL'
}

export default AlgorithmNames;
